### ISSUE TITLE
java.util.concurrent.CompletionException: org.eclipse.swt.SWTException: Invalid thread access

### ISSUE THREAD

**Issue by FreHu** [andau/abap-code-insight#15]
If I have ABAP traces focused and I do a where-used-list on something, the UI gets stuck in this state:
![image](https://user-images.githubusercontent.com/5097067/151807163-dab8170f-6bd2-45b4-b56a-1c4ab4feffb7.png)

[support.zip](https://github.com/andau/abap-code-insight/files/7971256/support.zip)
I originally reported this as an ADT issue but it turns out it's caused by the plugin (I can't reproduce using a clean ADT).
In the log file in the support.zip there are hundreds of errors like this:
```
!ENTRY org.eclipse.jface.text 4 0 2022-01-31 13:19:23.199
!MESSAGE org.eclipse.swt.SWTException: Invalid thread access
!STACK 0
java.util.concurrent.CompletionException: org.eclipse.swt.SWTException: Invalid thread access
 at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
 at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
 at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766)
 at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
 at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
 at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
 at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
 at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
 at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.eclipse.swt.SWTException: Invalid thread access
 at org.eclipse.swt.SWT.error(SWT.java:4907)
 at org.eclipse.swt.SWT.error(SWT.java:4822)
 at org.eclipse.swt.SWT.error(SWT.java:4793)
 at org.eclipse.swt.widgets.Widget.error(Widget.java:445)
 at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:365)
 at org.eclipse.swt.widgets.Widget.getData(Widget.java:539)
 at org.eclipse.jface.text.codemining.CodeMiningReconciler.mustInstall(CodeMiningReconciler.java:55)
 at org.eclipse.jface.text.codemining.CodeMiningReconciler.install(CodeMiningReconciler.java:38)
 at abap.codemining.plugin.AbapCodeInsightPlugin.reinitViewInReconcilers(AbapCodeInsightPlugin.java:58)
 at abap.codemining.plugin.AbapCodeInsightPluginHelper.reinitViewInReconcilers(AbapCodeInsightPluginHelper.java:20)
 at abap.codemining.editor.AbapCodeMiningProvider.lambda$0(AbapCodeMiningProvider.java:61)
 at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
 ... 6 more
```

**Comment by DariusRDev** [comment]
I have that issue too
